### ISSUE TITLE
A question about Hived

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/superbenchmark#525]
Hi @abuccts , Sorry for bringing up an unrelated question here due to the Hived repository has been archived.

Can Hived share same host in different VC?

for example, I have a 8GPU host, allocate 3GPU for vc1, and 5GPU for vc2.

Sorry for the inconvenience. Looking forward to your reply.

**Comment by abuccts** [comment]
> Can Hived share same host in different VC?

I think so, here's an example config (didn't test it):

```yaml
physicalCluster:
  cellTypes:
    X-GPU:
      childCellType: X
      childCellNumber: 1
    X-NODE:
      childCellType: X-GPU
      childCellNumber: 8
      isNodeLevel: true

  physicalCells:
  - cellType: X-NODE
    cellChildren:
    - cellAddress: 192.168.0.1

virtualClusters:
  VC1:
    virtualCells:
    - cellType: X-NODE.X-GPU
      cellNumber: 3
  VC2:
    virtualCells:
    - cellType: X-NODE.X-GPU
      cellNumber: 5
```
