### ISSUE TITLE
What is the proper way to write a rule.yaml for result summary?

### ISSUE THREAD

**Issue by DK-DARKmatter** [microsoft/superbenchmark#666]
**What's the issue, what's expected?**:
Trying to write a result summary yaml for the resnet50 raw data generated from tutorial. But get the following warning:
RuleBase: get metrics failed - model-benchmarks
Here's the summary_rule.yaml:
```
version: v0.11
superbench:
  rules:
    resnet:
      statistics:
        - mean
        - p90
        - min
        - max
      aggregate: False
      categories: Models
      metrics:
        - model-benchmarks/pytorch-resnet101/float16_train_step_time
```
**How to reproduce it?**:
sb result summary --data-file results-summary.jsonl --rule-file summary_rule.yaml --output-file-format md --output-dir ${something}

**Log message or shapshot?**:
[rule_base.py:75][WARNING] RuleBase: get metrics failed - model-benchmarks

**Additional information**:
